---
- name: Update and upgrade packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Node.js and npm
  apt:
    name: nodejs
    state: present

- name: Install pm2
  npm:
    name: pm2
    global: yes
