---
- name: Update and upgrade packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Add Node.js repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_13.x focal main
    state: present
    update_cache: yes
    filename: nodesource.list

- name: Install Node.js and npm
  apt:
    name: 
      - nodejs
    state: present

- name: Install pm2
  npm:
    name: pm2
    global: yes
