---
- name: Create folder
  file:
    path: /home/app
    state: directory

- name: Copy artifact to app folder
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/app

- name: Extract artifact
  shell: |
    cd /home/app
    tar -xvzf artifact.tar.gz

- name: Start the app
  shell: |
    cd /home/app
    npm install
    pm2 stop default
    pm2 start npm -- start