---
- name: Create folder
  become: true
  file:
    path: /home/app
    state: directory
    mode: 0755

- name: Copy artifact to app folder
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/app

- name: Extract artifact
  become: true
  shell: |
    cd /home/app
    tar -xvzf artifact.tar.gz

- name: Start the app
  become: true
  shell: |
    cd /home/app
    npm install
    npm run build
    pm2 stop default
    pm2 start npm -- start
